language: node_js
node_js:
- '7'
deploy:
  provider: firebase
  token:
    secure: auKdmuMLOdqOHerJIhga6+unpXKwedIH5oOeG2f9chPvrGdUNLKepBCkJh0z6UqLZ77QiDPwnWFZMS8fThVP8SKiB+qT2TYZb8XCZTTYnfE9eqSLTQLJ4Ho4jmNVVFElKxkL5O6d329N2fLMnZC88N4+TMPILpoLII/33RPKpFt6msDtd5tvn61k4jgxtMsUz1143UKZg0uVl6Zqk4B27H5xFM9UFHG4fe7Q+ewaRusEqLzMBL2ABqtQlnHuMj7kYZU+Z0AdgrsGSe/TF4lyPDDoAVwmOGyPA45fv30m76PG/yoM8n5VIJ9YJ9/DAvl90Ams7EOugUFaMIlflt+tY8eAqDsmn5RId35L7CyFZyfQd1YXY6pjeuXxaFZaD+hFdjqPxVgFWN4xmxYl1nSyvnVMpvGclisjTI8xTf7kDqUyrFOYtuetY+9Pa+KQzJHHtYoowyfMnqoe7aGP1ryAohO2LCc0bRAuEj68HJDf00Yj2lnEFA6CEoEGn6QvD63beblYQz5+7ujt5anqpkdrd/Og5vFP9gDiWsi8ZpKZ94SGTW/4/8YQfPPZpwaPb9Zdy/osmrCFEhZxyXWpaBymc7VbuZMKJx7nzjuql9kqHTXg73i4jZJeFASDibun8iPMsQGyqpmw1dGv/2iXqNubi8qk6eY0bK8vG8E/7pFWU0Q=
